pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    curl -o- -L https://yarnpkg.com/install.sh | bash	
    yarn install
    yarn test
  displayName: 'yarn install and yarn test'