version: '3.7'
services:
  bot:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - ./.env
    network_mode: 'host'

  lavalink:
    build:
      context: .
      dockerfile: Dockerfile-Lavalink
    restart: unless-stopped
    env_file:
      - ./.env_lavalink
    ports:
      - 7000:7000
    network_mode: 'host'

  redis:
    image: "redis:5-alpine"
    restart: unless-stopped
    command: redis-server --requirepass abooody888
    ports:
      - 6379:6379